RedBadgeMVCProject/Controllers/CartController.cs
using RedBadgeMVC.Data;
using RedBadgeMVC.Models;
using RedBadgeMVC.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RedBadgeMVCProject.Controllers
{
    public class CartController : Controller
    {
        Product product = new Product();
        public ActionResult Index()
        {
           
           
                return View();
           
        }

        public ActionResult Buy(int id)
        {
            ApplicationDbContext _db = new ApplicationDbContext();
 
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item { Product = _db.Products.Find(id), Quantity = 1 });
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++; 
                }
                else
                {
                    cart.Add(new Item { Product = _db.Products.Find(id), Quantity = 1 });
                }
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            int index = isExist(id);
            cart.RemoveAt(index);
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }

       //helper method item exist
        private int isExist(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++) 
                if (cart[i].Product.ProductId.Equals(id))
                    return i;
            return -1; 
        }

    }
}

RedBadgeMVCProject/Controllers/ReviewController.cs
using Microsoft.AspNet.Identity;
using RedBadgeMVC.Models.ReviewModels;
using RedBadgeMVC.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace RedBadgeMVCProject.Controllers
{
    public class ReviewController : Controller
    {

        private ReviewService CreateReviewService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new ReviewService(userId);
            return service;
        }
        // GET: Review
        public async Task<ActionResult> Index()
        {
            ViewBag.ReviewId = await GetRvAsync();
            var service = CreateReviewService();
            var model = await service.GetReviewAsync();
            return View(model);
        }
        public async Task<ActionResult> Details(int id)
        {
          
            var svc = CreateReviewService();
            var model = await svc.GetReviewByIdAsync(id);

            return View(model);
        }


        public async Task<ActionResult> Create()
        {
            var service = CreateReviewService();

            
            ViewBag.ProductId = await GetItemsAsync();
          


            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ReviewCreate review)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.ProductId = await GetItemsAsync();
                

                return View(review);

            }

            var service = CreateReviewService();

            if (await service.CreateReviewAsync(review))
            {
                TempData["SaveResult"] = "Your Review was created.";
                return RedirectToAction("Index","Product"); //returns the user back to the index view
            };
            ModelState.AddModelError("", "review could not be created.");//?
           ViewBag.ProductId = await GetItemsAsync();
           



            return View(review);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var service = CreateReviewService();
            var detail = await service.GetReviewByIdAsync(id);
            var model =
                new ReviewEdit
                {
                    ReviewId = detail.ReviewId,
                    Reviews = detail.Reviews,
                 

                };

            ViewBag.ProductId = await GetItemsAsync();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, ReviewEdit note)
        {
            if (!ModelState.IsValid) return View(note);
            if (note.ReviewId != id)
            {
                ModelState.AddModelError("", "ID Mismatch");
                ViewBag.ProductId = await GetItemsAsync();

                return View(note);
            }
            var service = CreateReviewService();
            if (await service.UpdateReviewAsync(note))
            {
                TempData["SaveResult"] = "Review was successfully updated.";
                return RedirectToAction("Index");
            }
            ViewBag.ProductId = await GetItemsAsync();

            ModelState.AddModelError("", "Menu could not be updated.");
            return View(note);
        }

        public async Task<ActionResult> Delete(int id)
        {
            var service = CreateReviewService();
            var detail = await service.GetReviewByIdAsync(id);
            return View(detail);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteReview(int id)
        {
            var service = CreateReviewService();
            await service.DeleteReviewAsync(id);
            TempData["SaveResult"] = "Your review was successfully deleted.";

            return RedirectToAction("Index");
        }

       //Helper method to bring data of item
        public async Task<IEnumerable<SelectListItem>> GetItemsAsync()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var Service = new ItemService(userId);
            var List = await Service.GetAllItemsAsync();

            var catSelectList = List.Select(
                                        e =>
                                            new SelectListItem
                                            {
                                                Value = e.ProductId.ToString(),

                                                Text = e.ProductName
                                            }
                                        ).ToList();

            return catSelectList;
        }


        public async Task<IEnumerable<SelectListItem>> GetRvAsync()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var Service = new ReviewService(userId);
            var List = await Service.GetReviewAsync();

            var revSelectList = List.Select(
                                        e =>
                                            new SelectListItem
                                            {
                                                Value = e.ReviewId.ToString(),

                                                Text = e.Reviews
                                            }
                                        ).ToList();

            return revSelectList;
        }
    }
}

RedBadgeMVCProject/Controllers/StoreController.cs
using Microsoft.AspNet.Identity;
using RedBadgeMVC.Models.StoreModels;
using RedBadgeMVC.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace RedBadgeMVCProject.Controllers
{

    
    public class StoreController : Controller
    {

        public StoreService CreateStoreService()
        {
             var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new StoreService(userId);
            return service;
        }
        // GET: Store
        public async Task<ActionResult> Index()
        {
            var service = CreateStoreService();
            var model = await service.GetStoresAsync();
            return View(model);
        }

        //Helper method
        public async Task<IEnumerable<SelectListItem>> GetItemAsync()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var storeService = new ItemService(userId);
            var storeList = await storeService.GetAllItemsAsync();

            var catSelectList = storeList.Select(
                                        e =>
                                            new SelectListItem
                                            {
                                                Value = e.ProductId.ToString(),
                                                Text = e.ProductName
                                            }
                                        ).ToList();

            return catSelectList;
        }

        //helper method
        public async Task<IEnumerable<SelectListItem>> GetReviewsAsync()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var Service = new ReviewService(userId);
            var List = await Service.GetReviewAsync();

            var reviewSelectList = List.Select(
                                        e =>
                                            new SelectListItem
                                            {
                                                Value = e.ReviewId.ToString(),
                                                Text = e.Reviews
                                            }
                                        ).ToList();

            return reviewSelectList;
        }
        public async Task<ActionResult> Create()
        {
            var service = CreateStoreService();

            
            ViewBag.ItemId = await GetItemAsync();
    
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(StoreCreate model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.AreaId = await GetItemAsync();

                return View(model);

            }

            var service = CreateStoreService();

            if (await service.CreateStoreAsync(model))
            {
                TempData["SaveResult"] = " Then Store Has Been Created.";
                return RedirectToAction("Index");

            }

            ModelState.AddModelError("", "Then Store Has not Been Created.");
            ViewBag.AreaId = await GetItemAsync();
           

            return View(model);
        }

        public async Task<ActionResult> Details(int id)
        {

            var svc = CreateStoreService();
            var model = await svc.GetStoreByIdAsync(id);

            return View(model);
        }
        public async Task<ActionResult> Edit(int id)
        {
            var service = CreateStoreService();
            var update = await service.GetStoreByIdAsync(id);
            var model =
                new StoreEdit
                {
                    StoreName=update.StoreName,
                    PhoneNumber=update.PhoneNumber,
                    Latitude = update.Latitude,
                    Longitude = update.Longitude,
                    Address=update.Address,
                    OpeningTime=update.OpeningTime,
                    ClosingTime=update.ClosingTime

                };
     
            ViewBag.ItemId = await GetItemAsync();
            ViewBag.ReviewId = await GetReviewsAsync();


            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, StoreEdit store)
        {
            if (!ModelState.IsValid) return View(store);
            if (store.StoreId != id)
            {
                ModelState.AddModelError("", "ID Mismatch");
                ViewBag.MenuId = await GetItemAsync();


                return View(store);
            }
            var service = CreateStoreService();
            if (await service.UpdateStoretAsync(store))
            {
                TempData["SaveResult"] = "Store Information Has Been Updated.";
                return RedirectToAction("Index");
            }
            ViewBag.MenuId = await GetItemAsync();


            ModelState.AddModelError("", "Then Store Has not Been Updated.");
            return View(store);
        }

        public async Task<ActionResult> Delete(int id)
        {
            var service = CreateStoreService();
            var details = await service.GetStoreByIdAsync(id);
            return View(details);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteStore(int id)
        {
            var service = CreateStoreService();
            await service.DeleteStoreAsync(id);
            TempData["SaveResult"] = "Restaurant Has Been successfully deleted.";

            return RedirectToAction("Index");
        }

    }
}

RedBadgeMVCProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia&effect=neon|outline|emboss|shadow-multiple">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/MyMainLayout.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
     

    <div class="container">
        <div class="row" style=">
            <div class="col-lg-6 col-sm-6 col-xs-6">
                <div class="Logo ">
                   <h3 class="font-effect-shadow-multiple" ><mark>Online</mark><i style="text-shadow: 2px 2px 4px black;">Shopping App</i></h3>
                    <br />
                    <h1 class="font-effect-neon" , style="background-color:black">Numidia Shop</h1>
                </div>
                @Html.Partial("_LoginPartial")
            </div>
          
        </div>
        <hr />
            <div class="=row" >
                <div class="=row" col-md-12>
                    <dic class="nav-menus" >
                        <ul class="nav nav-pills">
                            <li class="dropdown active">
                                <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Menu <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">




                                    <li><a href="https://localhost:44353/">Home</a>
                                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                                    <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                                    <li>@Html.ActionLink("Stores", "Index", "Store")</li>
                                    @if (User.IsInRole("Customer"))
                                    {

                                        <li>@Html.ActionLink(" Write Review", "Create", "Review")</li>
                                    }

                                </ul>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            @if (User.IsInRole("Customer"))
                            {
                                <li class="crt">@Html.ActionLink("ShoppingCart", "Index", "Cart")</li>
                            }

                            


                        </ul>

                    </dic>

                </div>

            </div>
      <br />

        <br />
        <br />
            <div>
                @RenderBody()
                <hr />
                <div class="footer">
                    <p class="text-center">&copy; @DateTime.Now.Year - Numidia Shop Application</p>
                    <p class="text-center">By Amel Mallem  Louda</p>
                    <div class="col-md-6 col-sm-6 copyright-right">


                    </div>
                </div>
            </div>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>
<style>

    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: rgb(22, 21, 21);
        color: white;
        text-align: center;
    }




    h1 {

        color: white;
        vertical-align: top;
        text-decoration: underline;
        text-transform: capitalize;
        text-shadow: 1px 1px;
        font-style: italic;
        font-size: 50px;
        font-family: "Sofia", sans-serif;
        border: 2px solid black;
        outline: white solid 10px;
        margin: auto;
        padding: 20px;
        text-align: center;
       

    }
    body {
        background-color: #e9b9b9;
        animation-name: example;
        animation-duration: 4s;
    }
    h3 {
        color: black;
        vertical-align: top;
        text-decoration: underline;
        text-transform: capitalize;
        text-shadow: 1px 1px;
        font-style: italic;
        font-size: 30px;
        font-family: "Sofia", sans-serif;
       
    }
    .crt {
        background-color: whitesmoke;
     
        font-family: "Sofia", sans-serif;
        color:black;
    }

</style>
   